name = "sundae/mint-chocolate-chip"
compiler = "v1.1.21"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundae/mint-chocolate-chip'"

[repository]
user = "sundae"
project = "mint-chocolate-chip"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.1"
source = "github"
