name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: mynth
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up nodejs
        run: bin/setup-node.sh

      - name: Run CI
        run: npm exec turbo ci
